field: c0fe6eff-5323-415f-81d9-4f9d42a07b66 # Story Content
fieldLayouts:
  0aa55bf9-2527-4724-bfab-1bb3986c4abc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f620927d-baf7-430a-a965-f1e9ea676b83 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52978b81-3e02-490b-95b0-f7bafa6addfd
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 518aea6d-af2d-4e4e-8d4b-a2ca618cd89c # Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c44ee2d-9529-49c3-b3b5-e01e045595d6
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 2b434a53-4cff-4bda-b391-9765450995c5
        userCondition: null
fields:
  518aea6d-af2d-4e4e-8d4b-a2ca618cd89c: # Style
    columnSuffix: hlykmjun
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: null
    name: Style
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Quotation marks'
            -
              - value
              - quoted
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  f620927d-baf7-430a-a965-f1e9ea676b83: # Text
    columnSuffix: acwqdamq
    contentColumnType: string(250)
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: 250
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 2
