field: 7ef9424e-9902-4930-9244-8d7f93d6dc4b # Story Team
fieldLayouts:
  3a8c2b50-7e32-41d5-83c9-21d75f45e2a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 806a473e-c6e7-42cd-a76b-758ed48b5a2b # Role
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eeffa0cc-99fc-426e-9068-a6a8ca83f87d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 07a23de3-b713-43fc-8310-d9191d851801 # Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 966c9041-7120-48ab-b245-08a059dc4e59
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: a52cf0ba-1c7e-4ffa-8a2f-b6b117d4ad16
        userCondition: null
fields:
  07a23de3-b713-43fc-8310-d9191d851801: # Name
    columnSuffix: tyztxjbk
    contentColumnType: string(240)
    fieldGroup: null
    handle: teamName
    instructions: null
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  806a473e-c6e7-42cd-a76b-758ed48b5a2b: # Role
    columnSuffix: yjyvjsph
    contentColumnType: string(240)
    fieldGroup: null
    handle: teamRole
    instructions: null
    name: Role
    searchable: false
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: teamMember
name: 'Team Member'
sortOrder: 1
