field: c0fe6eff-5323-415f-81d9-4f9d42a07b66 # Story Content
fieldLayouts:
  559f49d1-4223-417b-8771-4c2d10342363:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a4fff836-97c9-4c02-b970-c6f28915d8d0 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a79af11-6fbf-491c-af22-0bf89673c6cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 07238975-8b2d-4f77-97a4-f4aa1274bf93
        userCondition: null
fields:
  a4fff836-97c9-4c02-b970-c6f28915d8d0: # Text
    columnSuffix: efglxxyh
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 3
