color: null
fieldLayouts:
  716521cd-1f8b-43c2-a57a-167f06d78b92:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eca40b01-b3c6-4752-9c5b-9b7ad7146cc3
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T10:02:05+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 606b564d-9f76-4ff4-9e3f-ae35c49a0a84
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
            handle: isFeatured
            includeInCards: false
            instructions: 'Show in hero area of the article index page'
            label: 'Is Featured'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86d286af-7178-4170-9712-ed4fdeb98115
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 400d2e7a-d260-459d-b16d-bc388f093106 # Tagline
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8acfd02d-1d02-4e59-beec-18d239059a1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: a3142d55-72d3-47df-ba3b-36c89ca45781 # Writers
            handle: null
            includeInCards: false
            instructions: 'If external authors are to be shown.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e3280a5-4c35-42fd-bd22-91e98aa44675
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 05ab0680-2ccc-4a59-932a-07311f773d42 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d3c44f0-0734-4dd3-bfbf-1e430d5c992f
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3af461da-7661-47fa-8825-5985d85f1014
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: cardText
            includeInCards: false
            instructions: 'Displayed on index pages instead of the tagline'
            label: 'Card Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2452a3c-72e3-4735-a7a3-ec72b218bd3b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2edc5594-2c22-44b9-809f-f5265e581518
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 8785637f-8785-4fd2-86d2-9232d9674420 # Related Entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb6454ae-f57c-4e20-a8cb-41e09cac3e24
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1acf411e-8db3-4d3c-bad2-ac5bf3199455
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # SEO Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f4c8917-d962-4ba4-aaea-44a57e006a0d
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 24a9ee6d-5a1f-44b9-8979-5b7e812dce40
        userCondition: null
handle: article
hasTitleField: true
icon: newspaper
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
