color: null
fieldLayouts:
  6cce5763-28e6-451b-b8f3-84e06afb007c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3fe88ef8-94f6-4d86-b0c8-b418122b003a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 489e5502-a241-4b2e-97c5-d8a0220a72c6 # Target
            handle: null
            includeInCards: true
            instructions: null
            label: Target
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b419540-0e6e-4dbb-91c2-e8e28746954b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6193ce57-a570-451e-8124-ec3ba985b0b2 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c77ac28b-6775-46df-87a0-737959495778
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
            handle: primary
            includeInCards: false
            instructions: null
            label: Primary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 669a6d03-17c1-43da-82d2-76ada1c720da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e9aa5b9-9d0a-41ce-8f11-a8954fd8b777
        userCondition: null
handle: button
hasTitleField: false
icon: circle-dot
name: Button
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
