color: null
fieldLayouts:
  888f7fa5-0140-493b-8858-9fb47ffb1a32:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-03T10:09:14+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5e21a531-d8d0-423e-8d2d-52971d0fc4be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: eb61b6c1-d43a-4bf6-8091-bc71c44a9dcf # Entries
            handle: null
            includeInCards: true
            instructions: null
            label: Entries
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33044d64-3e02-42d1-8752-0dd647dfd38e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: 3d8293ac-fa84-47ed-befa-a41cb6315212 # Layout
            handle: null
            includeInCards: false
            instructions: null
            label: Layout
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfc562a7-8b95-4966-9334-1905e2c8e5a0
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 92206a48-c702-4bec-9596-93475e6fa0e6
        userCondition: null
handle: cards2
hasTitleField: false
icon: id-card
name: 'Entry Cards'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
