color: null
fieldLayouts:
  9be2749d-72b7-48fa-afa7-d1f2b7e7b091:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T10:02:05+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f3031dfd-8076-45b3-b767-8c73fe441e6b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: true
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c52a772-7ada-4789-95ab-2d88119fd740
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 7602aac5-c98e-44bd-8570-457a85b8abad # Criteria
            handle: null
            includeInCards: true
            instructions: "Must be valid JSON.\r\n\r\nBesides query criteria you can use `\"showMetaData\": true` , `\"layout\":\"card/cardlet\"` `\"width\":\"md/xl\"`"
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bc1c257-97ba-4296-805f-eb0121fcfa8c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 08f7545c-870e-4727-a418-660af19052ea # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8c89bf6-7e51-4624-ae7b-492a2591252b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9982bc63-ab67-470e-8a48-e935f6491770
        userCondition: null
handle: cards
hasTitleField: true
icon: address-card
name: Cards
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
