color: null
fieldLayouts:
  674b3078-0b6e-4166-8b6d-fa2a29979cd5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            dismissible: true
            elementCondition: null
            style: tip
            tip: 'This entry defines the caption and the info text for the cookie consent banner.'
            type: craft\fieldlayoutelements\Tip
            uid: 99ad2900-2a5d-4360-87c2-c325c6eaf1bd
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T10:02:05+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'The text shown on the cookie banner'
            label: Caption
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9cf6e525-4440-47ad-a2d9-5b46f85635c9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: false
            instructions: null
            label: 'Info Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57c0c9d4-8891-4638-9021-ee654e5f6724
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 84252758-c1ac-4b17-9042-f669ef34a75e
        userCondition: null
handle: cookieConsent
hasTitleField: true
icon: cookie-bite
name: 'Cookie Consent'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
