color: null
fieldLayouts:
  84cb4dd8-7ce4-4bd8-bf74-5b81b5354995:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7ff02fa0-08c2-482b-bc70-fc98c0c87231
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: db33cf09-8ba1-45f6-9cc0-3e855cbcb809 # Template
            handle: null
            includeInCards: false
            instructions: null
            label: Template
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c521ab82-40b0-45c1-bc2a-14acb42fab5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 605e973b-b2e9-4421-9f1a-80d4cddc0cf0 # Parameter
            handle: null
            includeInCards: true
            instructions: null
            label: Parameter
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68d74649-9098-4dc8-8c47-901bb525658a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03deb3d2-8f87-45f0-9002-ee9426351f3d
        userCondition: null
handle: dynamicBlock
hasTitleField: false
icon: null
name: Dynamic
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
