color: null
fieldLayouts:
  b72cbe2f-4cf2-4f3c-b7c6-587ba14afe04:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1b25bada-aeba-431f-a22e-1bb1d2d34f07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02d2113e-298a-47c6-a40e-413a682ac7c5 # Question
            handle: null
            includeInCards: true
            instructions: null
            label: Question
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 569ed2bd-b8ab-4cb3-be35-832e0ef9bd26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3cb8a841-f986-4959-8f1a-c44fe16ff8d1 # Answer
            handle: null
            includeInCards: false
            instructions: null
            label: Answer
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f0c8d34-3e23-4f11-b62a-a5e853cca746
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5955d950-edfa-4c10-b604-93c576a95048
        userCondition: null
handle: faq
hasTitleField: false
icon: question
name: FAQ
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
