color: null
fieldLayouts:
  77aa81b2-2f13-4500-a96b-fe51b6d2aa91:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            heading: Summary
            type: craft\fieldlayoutelements\Heading
            uid: 1ac65509-f53e-467d-9e65-b1048aa5a333
            userCondition: null
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: 4a8239eb-1b66-44e0-bd66-5a65d44b0727 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: Icon
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 837520f2-2a64-4eef-9ff1-ed161ce2e08c
            userCondition: null
            warning: null
            width: 25
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T08:38:44+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8bef2e0c-9704-43e1-9e9d-c489e117028f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: 400d2e7a-d260-459d-b16d-bc388f093106 # Tagline
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11959022-4eb6-4ff0-8212-4d1c7defb405
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            heading: Details
            type: craft\fieldlayoutelements\Heading
            uid: 6f6f844a-6d90-4e40-a550-e6027d834ca7
            userCondition: null
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 239531cc-8ca8-45f8-a375-4c338978c7e5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a95a9452-d092-42ed-97b6-444053cded5c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 10f2215c-c1a4-40c7-9a2b-f280ed1a5130
        userCondition: null
handle: feature
hasTitleField: true
icon: message
name: Feature
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: language
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
