color: null
fieldLayouts:
  77aa81b2-2f13-4500-a96b-fe51b6d2aa91:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8bef2e0c-9704-43e1-9e9d-c489e117028f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a8239eb-1b66-44e0-bd66-5a65d44b0727 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: Icon
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 837520f2-2a64-4eef-9ff1-ed161ce2e08c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 0415563b-b1b2-4756-9f8d-0b86d005deb1 # Heading
            handle: null
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a64923b8-6763-4e78-935d-3882ca5730ac
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: cf1158bf-b524-4684-9147-0ca8295ba477 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85b8572e-3fa3-4ea9-b2c4-1a823bc5b32d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 10f2215c-c1a4-40c7-9a2b-f280ed1a5130
        userCondition: null
handle: feature
hasTitleField: false
icon: message
name: Feature
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
