color: null
fieldLayouts:
  990b01ed-53fa-475d-a496-910b85940b4c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58725d83-3903-4300-9f2f-5654fea3ba13
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T11:37:24+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a60cca6a-1b05-4fe3-b17f-6763c3bb8af1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: true
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b293d9a7-15f6-4a38-b32f-fcffa3b68650
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 10ed7f90-b5ae-414d-a27e-ce0c2e680d27 # Features
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 695a3d4a-4c5a-4898-948c-5b5f093ddd21
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01241459-b612-4f2f-972b-31212a86a37a
        userCondition: null
handle: features
hasTitleField: true
icon: messages
name: Features
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
