color: null
fieldLayouts:
  748d84c2-377a-405b-952d-19cf015d9be1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 382153af-92e9-4794-b6b6-14af1366b9e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c39cdb5-26f9-49ca-9bb4-445a28a61ddf # Images
            handle: null
            includeInCards: false
            instructions: null
            label: Images
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01b1bc33-ec15-4de4-8a4c-2545d85730f4
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: b40353f4-de5f-4006-813a-15494e63e104 # Align
            handle: align
            includeInCards: true
            instructions: null
            label: Align
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ba21dbf-6fb8-46cf-bccb-ac4e5ce875a0
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 5f7c731a-45a8-476b-b628-a9d22cabe59b
        userCondition: null
handle: gallery
hasTitleField: false
icon: images
name: Gallery
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
