color: null
fieldLayouts:
  22cc67d9-e2e7-4e8d-b385-a1bc4c43835e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T01:17:57+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3b4ac14e-f220-4b61-ac33-7670ff958a48
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2509986-6b97-4fd2-9400-514636d0431e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition: null
            fieldUid: 1de27fd9-bda6-4977-8d43-b36ef6813c60 # Level
            handle: null
            includeInCards: false
            instructions: null
            label: Level
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb338c21-2796-4b2c-b622-b82738a3be2f
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: be6789a7-64de-4d8d-a3a8-38a75763af9b
        userCondition: null
handle: heading
hasTitleField: false
icon: text
name: Heading
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
