color: null
fieldLayouts:
  aee8b4ab-cda8-4a5f-a7a3-f3efcc1d74be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            handle: null
            includeInCards: false
            instructions: 'Above the title'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0e37d1a-5d23-4756-a738-3400c2f373fc
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-05T13:40:37+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Hero Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 96ef4529-1abd-4c5c-9487-44ff965f7611
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 80fa81e4-1f78-4d88-b733-f565d1f5b9bd # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9160991b-cdd7-44e5-9fa0-10d6f3bd48a9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da877cca-c912-473e-a17f-f627b4b74c3c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            heading: CTA
            type: craft\fieldlayoutelements\Heading
            uid: e46dd8dc-23df-436d-8254-fb77a656369a
            userCondition: null
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 08f7545c-870e-4727-a418-660af19052ea # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cd30983-5d8a-4c19-8d71-61e410aa5ff3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            heading: Layout
            type: craft\fieldlayoutelements\Heading
            uid: b5509a70-3403-4dd3-a8db-77f6adecd776
            userCondition: null
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 655243f7-46a2-42c0-8de4-188017c31d53 # Hero Area Template
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f384736a-6635-4904-a48d-5d10367a48cc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f404ecd-d5b1-42b3-a674-5d6a0745c5f5
        userCondition: null
handle: heroArea
hasTitleField: true
icon: table-layout
name: 'Hero Area'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
