color: null
fieldLayouts:
  73ac25bc-ace9-4aa6-ba1d-9211b5c06027:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 664638fa-08e5-4b6b-a081-df5801ca5846
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 735b5e6e-8026-4de4-8e32-14e03d975565 # Image
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9b2074e-9c0c-42ca-912b-da62df8b651a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a05a3ce8-0bcb-4e36-abb0-1338754baec1 # Image Align
            handle: align
            includeInCards: false
            instructions: null
            label: Align
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfd393f4-33ce-4f02-9180-ef4e7f9263b0
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 871e0a60-ea70-4650-91f2-746c9bc2de41 # Aspect Ratio
            handle: aspectRatio
            includeInCards: false
            instructions: null
            label: 'Aspect Ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 317ec3fc-8fee-45dc-a2e6-2770b50e0ead
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6193ce57-a570-451e-8124-ec3ba985b0b2 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ff7f6de-01d6-437d-b1b9-a3235372ddda
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 94b76905-09aa-4aeb-82a0-222f592d42f8 # Show in Sites
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad355451-2097-4b8f-be9c-5e40aa941447
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c7f52bda-4083-406b-982c-63def615500a
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
