color: null
fieldLayouts:
  3a8856ac-a762-4fea-a9d5-d9055a204ff4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T11:37:24+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2f713fcc-62a6-44fb-b1cd-f4dd9e115121
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
            handle: showLink
            includeInCards: false
            instructions: 'Whether a link to this page will be shown in menus'
            label: 'Show Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75efab5d-2f47-454a-8a41-b9291a707708
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a6689c8-93d9-41b5-b872-a51dc5b5c453
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 008771ec-f7a7-471e-a023-0df6cd544b8d
        userCondition: null
handle: legal
hasTitleField: true
icon: scale-balanced
name: Legal
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
