color: null
fieldLayouts:
  1ca0bb2f-93b6-407d-883c-8b3dac20fa95:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: true
            elementCondition: null
            style: tip
            tip: 'Does not have it''s own content, it creates a primary navigation item that shows a dropdown.'
            type: craft\fieldlayoutelements\Tip
            uid: 893bbc97-6474-49e3-a197-afc4ddbbee94
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98cd0278-9482-4133-90ab-5f54c1b26c70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
            handle: showStructureNavigation
            includeInCards: false
            instructions: 'Show navigation for this entry and it''s descendants'
            label: 'Show Structure Navigation'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aced4d79-6d7d-44d1-a3c7-e12c9b7c21f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0e5d9cbb-86fe-4e68-9632-75129c02b391 # Short Text (not translatable)
            handle: navItemTemplate
            includeInCards: false
            instructions: 'The template that renders the dropdown panel. If empty, the direct descendants of this entry will be shown'
            label: 'Nav Item Template'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df194adb-97e3-4ec3-a8aa-228d88c9834f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d985bf75-b350-4220-b741-8a42c5efbb01
        userCondition: null
handle: navItem
hasTitleField: true
icon: bars
name: 'Nav Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
