color: null
fieldLayouts:
  32ea56ce-b794-4d33-a3fa-b0d4abc5434a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-03T10:09:14+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3b4a01ba-4183-4c56-b64c-fd38ebf1a8b3
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: e2e51276-3783-49cb-9ed0-22ae364fd49a # Menu Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22f7e433-e0e3-4fc3-a9f7-1c3ed033dbec
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: 400d2e7a-d260-459d-b16d-bc388f093106 # Tagline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afb2145e-1322-44eb-b30c-906dba6ce34e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            heading: 'Header Layout'
            type: craft\fieldlayoutelements\Heading
            uid: 86e849d3-dc2d-4999-b8e6-2cbacb705a41
            userCondition: null
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a53a4c9c-87e2-438f-abf9-8e5cde9cb4a1
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
            handle: showHeroArea
            includeInCards: false
            instructions: 'Show hero area with featured image'
            label: 'Show Hero Area'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89de4e9a-2be6-46e6-8d8c-abed7dcfbfb8
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
                  layoutElementUid: 89de4e9a-2be6-46e6-8d8c-abed7dcfbfb8
                  uid: 528e76af-036f-42d9-9c3f-2171834339e1
                  value: false
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 75980a78-5a14-4d80-8e9c-b0616d62e02e # Hero Area
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7c1f569-eece-4729-a5ae-dd7d0ad51ba7
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: 655243f7-46a2-42c0-8de4-188017c31d53 # Hero Area Template
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 163be9a2-b434-45f8-a0c2-0638eaaf2717
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: 3028b2cb-b21b-42e9-acb2-de4f11747015
            userCondition: null
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2964be67-d0ec-4745-b6a9-f6a7613c5d04
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: 0e5d9cbb-86fe-4e68-9632-75129c02b391 # Short Text (not translatable)
            handle: pageTemplate
            includeInCards: false
            instructions: null
            label: 'Page Template'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4661c976-44fd-41e5-9b88-0acda615da5d
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 3e5d4b25-803e-4a54-8e02-ac9238e449c4
        userCondition: null
handle: pageTemplate
hasTitleField: true
icon: page
name: 'Page Template'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
