color: null
fieldLayouts:
  35aac453-6959-4771-9712-cb98f5a45da0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T01:17:57+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23e88f1c-1490-4ee0-9514-ebc54e2dfce1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\LevelConditionRule
                  maxValue: ''
                  operator: '='
                  step: 1
                  uid: 26bc4c45-6da3-484a-b16e-a9111915ed6b
                  value: '2'
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: e2e51276-3783-49cb-9ed0-22ae364fd49a # Menu Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 606761c5-6bcf-4d72-acc4-08e97d2f6046
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition: null
            fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
            handle: showStructureNavigation
            includeInCards: false
            instructions: "Show navigation for this entry and it's descendants"
            label: 'Show Structure Navigation'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9e80086-0e68-4369-84d0-a307036c5dcd
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition: null
            fieldUid: 400d2e7a-d260-459d-b16d-bc388f093106 # Tagline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81811389-64d6-4ab9-8eee-543834b5b690
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition: null
            fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
            handle: showHeroArea
            includeInCards: false
            instructions: null
            label: 'Show Hero Area'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11f551bb-d0f6-4e7d-b782-0b1516e6c8c9
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
                  layoutElementUid: 89de4e9a-2be6-46e6-8d8c-abed7dcfbfb8
                  uid: 5ca383fd-6cd2-4a61-96d5-6780fd10a6c2
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e30e2dd-1bb2-40b0-a4d3-e70ab95d47da
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3749e2b-fda8-411d-b55e-306b27632de2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 805db790-0bd9-4591-905d-34133e531ece
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T01:17:57+01:00'
            elementCondition: null
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # SEO Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3fda0e8-90e0-4c53-955e-d0be31931b2e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 98c055d9-9b56-486b-b2d0-99fc3dee847e
        userCondition: null
handle: page
hasTitleField: true
icon: page
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
