color: null
fieldLayouts:
  52ae468f-4303-4b14-9e54-685363b9f8f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T09:47:25+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ab9ab1d4-82b1-4045-8fab-ae96df3a9c72
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:47:25+02:00'
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            handle: null
            includeInCards: true
            instructions: null
            label: 'Job description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecac4a8a-9a60-4a3e-8cd8-f86d99cdd888
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:47:25+02:00'
            elementCondition: null
            fieldUid: 78014c80-5d4b-4253-ae59-80f00e516c86 # Photo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5233774-4db2-4e16-a351-d06de8f17a16
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:47:25+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dec0bb8c-7cf5-471e-9ce4-8fe71124d001
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:47:25+02:00'
            elementCondition: null
            fieldUid: bf3d514d-a34d-41d6-bb20-61c6d8119820 # Social Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cd6fe2e-df5d-45f2-a05c-3cc65ce885f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 779de023-085f-44a4-b2c3-1e816b25320e
        userCondition: null
handle: person
hasTitleField: true
icon: person
name: Person
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
