color: null
fieldLayouts:
  78605b6a-aeb7-4aa5-b1b6-00c3ab01fa3e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-03T10:09:14+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: defc73e4-b96a-4c79-bcab-936391f0bc2b
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: 7fb04ffe-73af-49d3-a840-c4c224d40dcf # Toggle
            handle: showLink
            includeInCards: false
            instructions: 'Whether a link to this page will be shown in menus'
            label: 'Show Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01aa744b-3a6d-4899-a883-cd97c16e6041
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-03T10:09:14+01:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d2803d5-4b1d-4f61-b844-36d6d67ae589
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7624a4ed-026d-45c4-9431-6fb52daac8b0
        userCondition: null
handle: privacy
hasTitleField: true
icon: section
name: Privacy
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
