color: null
fieldLayouts:
  a42b8c07-6894-4c9e-8bb1-9f1d7928cdc3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T09:38:20+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 48bf8402-c755-47f2-8d9f-0f37bfc2afcc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:38:20+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bcc68c2-14a0-4607-b4f0-8040078dc7dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:38:20+02:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: cite
            includeInCards: false
            instructions: null
            label: Cite
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 445e5821-eb2f-40d7-b3d8-4ad91943a99f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:38:20+02:00'
            elementCondition: null
            fieldUid: 2a4edc9c-3738-408b-bf08-b557bc12ee6e # Style
            handle: null
            includeInCards: false
            instructions: null
            label: Style
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15a637eb-c7ad-4f55-8838-3d4b052bc61c
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: a7e83c0a-3aa6-46d1-9a94-6a845b87b5ce
        userCondition: null
handle: quote
hasTitleField: false
icon: quotes
name: Quote
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
