color: null
fieldLayouts:
  4ab2876b-7cb0-4e57-beb1-68a0faac922c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'This entry triggers a redirect to a random article.'
            type: craft\fieldlayoutelements\Tip
            uid: 8867beeb-7c97-4975-9f10-2daf4db85cd8
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T08:38:44+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ff8246a1-4f5b-49c7-ba52-962b4ae6683e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: acbb32aa-9881-4fff-b6e7-daf47ed909c0
        userCondition: null
handle: random
hasTitleField: true
icon: bolt
name: Random
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
