color: null
fieldLayouts:
  a3a223e7-de48-4b77-9d19-7fd60f6e0131:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9f92c5da-6e40-4bc4-a642-f5ba72247d8e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b0cfc7f4-d446-41bb-87ab-dc16b1481540 # Alternative Title
            handle: null
            includeInCards: true
            instructions: null
            label: 'Alternative Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc0be446-128a-4e51-81f8-7ba23b91142a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c7e95a7-7a87-46ad-974e-8ce3846ef68b # Description
            handle: null
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07ad2848-4e40-43cc-bd11-72d61f7141a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 34581043-4880-49b9-b16a-cba691fa21f3 # SEO Fields Settings Image
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02950812-f12a-42cd-a1f7-e20bd7f8f089
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90724a6b-55ad-446f-be50-7aea7e1fb067 # Robots
            handle: null
            includeInCards: false
            instructions: null
            label: Robots
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49714142-2f02-44e9-a475-5dd1f7d878ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9fc96fef-7f12-483f-aee5-9c03aece82ad
        userCondition: null
handle: settings
hasTitleField: false
icon: gear
name: Settings
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
