color: null
fieldLayouts:
  a3a223e7-de48-4b77-9d19-7fd60f6e0131:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T08:38:44+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9f92c5da-6e40-4bc4-a642-f5ba72247d8e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: alternativeTitle
            includeInCards: true
            instructions: null
            label: 'Alternative Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77efe43a-3799-4124-973e-b68f77509f29
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: description
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e85d0134-6b1d-49d8-bdb5-918b564ca9de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: 34581043-4880-49b9-b16a-cba691fa21f3 # Image
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02950812-f12a-42cd-a1f7-e20bd7f8f089
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: 90724a6b-55ad-446f-be50-7aea7e1fb067 # Robots
            handle: null
            includeInCards: false
            instructions: null
            label: Robots
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49714142-2f02-44e9-a475-5dd1f7d878ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9fc96fef-7f12-483f-aee5-9c03aece82ad
        userCondition: null
handle: settings
hasTitleField: false
icon: gear
name: Settings
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
