color: null
fieldLayouts:
  9e769ade-981f-4d62-8a34-a99331cadaaa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            dismissible: true
            elementCondition: null
            style: tip
            tip: 'This entry defines global settings for the entire site.'
            type: craft\fieldlayoutelements\Tip
            uid: f9a8ab04-fba7-4fac-b977-274aa9c15ed4
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T11:37:24+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'As used in the front end'
            label: 'Site Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b9e87b55-ef6f-421f-b975-d74962ec607e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: copyright
            includeInCards: true
            instructions: null
            label: Copyright
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01c219f0-d181-4b4f-8c9e-1d8988993a97
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: ebe8548f-7f01-49b6-af98-56da49668e79 # Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9700ff7-ea01-4a92-a652-11516d38aee1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Default Featured Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd840675-51c0-41da-ab17-eba26aad36d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b6f55c4a-511b-4037-8d75-358f4bc1ba4f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 324e8b16-2907-4fe0-99bb-9d46526eec07 # Addresses
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c59308ea-84a6-4982-bf94-3d1a3a6b005f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 0e5d9cbb-86fe-4e68-9632-75129c02b391 # Short Text (not translatable)
            handle: phoneNumber
            includeInCards: false
            instructions: null
            label: 'Phone Number'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 672c1ddc-ab4f-47fd-8613-1dacd55a0b0f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: bbe2ff0f-6056-4848-80de-3070bb80294d # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afc3147d-9f54-4d55-80a1-eac004f83b9e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: bf3d514d-a34d-41d6-bb20-61c6d8119820 # Social Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d312e13-bf8f-44fb-a9e7-002b366c9eaa
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Info'
        uid: 73e483b6-dbd7-4378-9ce8-e0e6f90046da
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 621ad41b-f019-4e95-96aa-49f8c56482db # SEO Descriction
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faf46b13-13e0-4d49-8f58-4c843e7a37b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 80fa81e4-1f78-4d88-b733-f565d1f5b9bd # Image
            handle: seoImage
            includeInCards: false
            instructions: null
            label: 'SEO Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8bf49b7-b7c6-404b-ae71-73b5a7a2842d
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4733ec62-0324-4ca3-867d-0f59b8c54754
        userCondition: null
handle: siteInfo
hasTitleField: true
icon: gear
name: 'Site Info'
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: none
