color: null
fieldLayouts:
  78018d7c-8136-497e-87b9-3fb38825d4a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-23T16:10:53+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3c6ed33c-2c97-41fa-94ab-6c26578787b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-23T16:10:53+02:00'
            elementCondition: null
            fieldUid: 8c826eca-f376-4f7a-92d6-307faddea123 # Image
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23ab5238-4763-45f4-9563-bfefc9efce5c
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-23T16:10:53+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf18dc44-ec33-4e9b-97b1-4ffd698ada45
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-23T16:10:53+02:00'
            elementCondition: null
            fieldUid: 6ecb9b3b-4c70-44df-a0ef-88a4ae27beec # Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f46e648-4ac8-4af4-9ee9-394557dd3aec
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 70d18cd1-3e82-4fb3-98f0-17d01de281be
        userCondition: null
handle: storyCover
hasTitleField: false
icon: image
name: 'Story Cover'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
