color: null
fieldLayouts:
  24f25949-87b5-4e02-9006-d0231bc96c08:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6503a5f6-b2fa-436f-be6c-61d20136c4cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5bf7587-80f3-47bf-8e22-d1d8bbcf11ee # Story Title Template
            handle: null
            includeInCards: false
            instructions: null
            label: 'Title Template'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a693085b-fb07-4cb3-8d63-2c625a47a120
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6390c85f-7ed1-4786-8866-8d9501505250
        userCondition: null
handle: storyTitleBlock
hasTitleField: false
icon: text
name: 'Story Title Block'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
