color: null
fieldLayouts:
  4e536a94-a8cb-4bfa-a89f-0e3fcbda0db8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-07T10:02:05+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f4eaf6e0-7150-4d52-8024-c1c5d01d5895
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-07T10:02:05+02:00'
            elementCondition: null
            fieldUid: 367161e2-88c5-4828-92ff-9124ef18da28 # Image
            handle: image
            includeInCards: true
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3009c528-5ec1-4b09-9b81-8da3e7b3ba24
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a957e8d-863e-4c3a-b4e0-0af2ebfbd4d1
        userCondition: null
handle: storyImage
hasTitleField: false
icon: image
name: 'Story Image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
