color: null
fieldLayouts:
  0aa55bf9-2527-4724-bfab-1bb3986c4abc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-25T15:51:25+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 128f819f-c494-4a00-aba9-eaf87c84e02f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-25T15:51:25+01:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17623bb2-e5b7-4e67-9eda-f799a455b4c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-25T15:51:25+01:00'
            elementCondition: null
            fieldUid: 518aea6d-af2d-4e4e-8d4b-a2ca618cd89c # Style
            handle: storyHeadingStyle
            includeInCards: false
            instructions: null
            label: 'Heading Style'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c44ee2d-9529-49c3-b3b5-e01e045595d6
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 2b434a53-4cff-4bda-b391-9765450995c5
        userCondition: null
handle: storyHeading
hasTitleField: false
icon: text
name: 'Story Heading'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
