color: null
fieldLayouts:
  3a8c2b50-7e32-41d5-83c9-21d75f45e2a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-23T11:57:58+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eda159a9-5071-4e5c-b046-7befcec3cc8b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-23T11:57:58+01:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: teamRole
            includeInCards: true
            instructions: null
            label: Role
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b30f85e-5c17-4bfc-936c-f6c0459abbee
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-11-23T11:57:58+01:00'
            elementCondition: null
            fieldUid: 0e5d9cbb-86fe-4e68-9632-75129c02b391 # Short Text (not translatable)
            handle: teamName
            includeInCards: true
            instructions: null
            label: Name
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 769616de-493e-4ede-a94c-a60c8a2769ac
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: a52cf0ba-1c7e-4ffa-8a2f-b6b117d4ad16
        userCondition: null
handle: teamMember
hasTitleField: false
icon: user
name: 'Team Member'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
