color: null
fieldLayouts:
  003bfc39-e6ae-40d1-aea0-ee455fe5cee0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T08:38:44+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 489dda23-5a11-4abe-83d5-66d212aca425
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c5ff045-0522-47bc-befe-3b1f476b71dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:38:44+02:00'
            elementCondition: null
            fieldUid: ee886fff-a72a-4a22-b217-f878c7f53ffe # Persons
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc7e4efd-dbe3-49ba-b46a-85ec440af8c9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f72988be-59c7-495b-9b8b-bb9a7aabda83
        userCondition: null
handle: team
hasTitleField: true
icon: users
name: Team
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
