color: null
fieldLayouts:
  574f0277-818f-4e79-a293-e007dc51855a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 262c090c-dbf5-4ba4-b2f0-1b247a92f4ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5a7f843-c933-4984-891f-62efa78f8418
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80fa81e4-1f78-4d88-b733-f565d1f5b9bd # Image
            handle: null
            includeInCards: false
            instructions: 'If blank, the persons photo will be used'
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d09db5d5-776d-4091-84fa-a1b65b31e5a7
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6bc951bf-74b3-4218-b3aa-dc427967abe9 # Person
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0513742-f153-46a0-aa76-49da5d5fda1e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 013c1232-8bf7-4c1f-80dc-d456db31f159 # Testimonial Style
                  operator: in
                  uid: b66ce35f-6fca-4d62-84f1-6a88353d4044
                  values:
                    - overlappingImage
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 33518692-b4a6-4ac6-9423-5631e47f87a5 # Postion Align
            handle: align
            includeInCards: false
            instructions: 'Position of the image'
            label: Align
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 765b2eb8-69da-4a9b-957a-0375514fb057
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 013c1232-8bf7-4c1f-80dc-d456db31f159 # Testimonial Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d42963b-7bd4-418b-aaa7-798cff80a826
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac442f84-3e1d-40cb-8fa8-aff61224880e
        userCondition: null
handle: testimonial
hasTitleField: false
icon: user
name: 'Single Testimonial'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{body[:50]} - {person.one.title}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
