color: null
fieldLayouts:
  322df68d-3b25-4b3f-bcb5-730cfbbcbfbc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fd43f6db-2919-45fc-9eec-b3d9ae99f267
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a98d7f63-bd66-4956-a762-f934ef01bf18
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 567dfff7-4e6b-43d6-bb7b-a486901aa8d8
        userCondition: null
handle: text
hasTitleField: false
icon: paragraph
name: Text
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
