color: null
fieldLayouts:
  4daa1c40-4831-4547-b632-2379eac5a701:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-12T09:38:20+02:00'
            dismissible: true
            elementCondition: null
            style: tip
            tip: 'Use the slug of this entry to access it in your templates. Make sure the slug is identical on all sites!'
            type: craft\fieldlayoutelements\Tip
            uid: 2900f3d8-16f9-4718-bb30-101f16ce86cd
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T09:38:20+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 630da346-fc2d-48b1-91b1-de26022d0286
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:38:20+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: body
            includeInCards: true
            instructions: null
            label: Body
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e21740b-9f0f-4cc0-8502-58f603c61423
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: c7003a67-06d5-4802-8e66-57a4c86154e6
        userCondition: null
handle: textModule
hasTitleField: true
icon: font-case
name: 'Text Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
