color: null
fieldLayouts:
  559f49d1-4223-417b-8771-4c2d10342363:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 84c94bdf-cb7b-473f-b26e-fe8671e727a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4fff836-97c9-4c02-b970-c6f28915d8d0 # Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a79af11-6fbf-491c-af22-0bf89673c6cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 07238975-8b2d-4f77-97a4-f4aa1274bf93
        userCondition: null
handle: text2
hasTitleField: false
icon: null
name: 'Text 2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
