color: null
fieldLayouts:
  e463be1c-a88a-40f9-9d31-e772cc9690ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48681c9a-24c8-4695-b31e-b58218980afb
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T11:37:24+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 559dda1e-9a33-4857-aaf3-ac1bcce65160
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: bff90088-ffd2-4e25-aa4d-d9dc27cad56a # Column Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c261cd2-15b9-4e86-bb8a-bcff70c0d522
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 80fa81e4-1f78-4d88-b733-f565d1f5b9bd # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64580eeb-e575-4374-9ba3-0e7fa0745a9a
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 79e20dfb-3edc-467c-a1e9-826c362d54b6
        userCondition: null
handle: twoColumnsWithImage
hasTitleField: true
icon: table-columns
name: 'Two columns with image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
