color: null
fieldLayouts:
  a4d95bc5-a2a6-48a5-9a99-26744ed5f1e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-05T13:40:37+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 25ef3dc8-029f-4c31-a0c6-2bb396330295
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: heading
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d37648f6-9fb9-4935-90af-a20e0a7c79e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 354b3c11-ae38-4fae-8017-8ddced25fecd # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e83f3d05-007e-4dd1-a792-243ca8ae5731
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 0e5d9cbb-86fe-4e68-9632-75129c02b391 # Short Text (not translatable)
            handle: key
            includeInCards: false
            instructions: 'Parameter ?v= from YouTube Url, e.g. _hoGpYyn4Bs'
            label: Key
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 880ffed4-8941-4a31-af0e-4986d61d3ee2
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: f3c6560d-3487-4f65-a4f9-ac2926397b57 # Aspect Ratio
            handle: null
            includeInCards: false
            instructions: null
            label: 'Aspect Ratio'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8806a410-cbec-45b7-8995-a103ccf8be5a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-10-05T13:40:37+02:00'
            elementCondition: null
            fieldUid: 94b76905-09aa-4aeb-82a0-222f592d42f8 # Show in Sites
            handle: null
            includeInCards: false
            instructions: null
            label: 'Show in Sites'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7db901fb-2a7b-4dee-96b1-aaf2ead2b1e5
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 5bb92117-3e5a-4406-a147-f4738c98d7c6
        userCondition: null
handle: youtubeVideo
hasTitleField: false
icon: video
name: 'YouTube Video'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
