altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  741edb78-e490-4426-a3ca-1f7033331ddf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T11:37:24+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 722dd964-b9a0-4b55-b413-f2954c98c88c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-11-13T11:37:24+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: true
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: f206efd1-d79c-41aa-9bba-a3b042943690
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 0a4ca680-269a-45f0-8eac-eada97e7dc29 # Single Line Text
            handle: caption
            includeInCards: true
            instructions: 'For images: This is the information that must be legally displayed, usually the name of the photographer, for microstock images the name of the service if applicable. Leave blank if nothing is to be displayed on the website.'
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b328b24f-e559-4f7e-81f1-91558223fa32
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: 0e5d9cbb-86fe-4e68-9632-75129c02b391 # Short Text (not translatable)
            handle: copyright
            includeInCards: false
            instructions: null
            label: Copyright
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59160145-d4b7-4870-8b24-d89a57f4595c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T11:37:24+01:00'
            elementCondition: null
            fieldUid: c5912111-be84-47af-8f06-5df24eb99d67 # Text (not translatable)
            handle: imageSource
            includeInCards: false
            instructions: 'Internal only. Name of a Microstock service of agency, if it differs from the copyright notice.'
            label: 'Image Source'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8af1c8d-81cd-451a-8b21-e62053735ae0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 22529198-b0c8-440f-aa3e-f169a9e3f551
        userCondition: null
fs: $PROTECTEDVOLUMES_FS
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: $IMAGE_TRANSFORM_FS
transformSubpath: images
