columnSuffix: null
handle: addresses
instructions: null
name: Addresses
searchable: false
settings:
  maxAddresses: 3
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
