columnSuffix: null
handle: buttons
instructions: null
name: Buttons
searchable: true
settings:
  createButtonLabel: 'New button'
  entryTypes:
    - dfe86fae-c542-4ae2-8b07-16d57c206b16 # Button
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
