columnSuffix: dlfjxjug
handle: cite
instructions: null
name: Cite
searchable: true
settings:
  byteLimit: null
  charLimit: 60
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
