columnSuffix: null
handle: columncontent
instructions: null
name: 'Column Content'
searchable: true
settings:
  createButtonLabel: 'New content block'
  defaultIndexViewMode: cards
  entryTypes:
    - ac457f93-1a50-473e-9983-a899a7f0bed7 # Heading
    - 81e6a0d6-13c5-47ad-a9e6-c2181276db9c # Text
    - 7b8b6f04-9d76-4b26-8276-96a80183750e # Quote
    - 69164545-5879-454d-a57e-f703ca431331 # Image
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
