columnSuffix: null
handle: emailSender
instructions: null
name: 'Email Sender'
searchable: false
settings:
  validationRule: ''
  variableName: EMAIL_SENDER
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\EnvironmentVariableField
