columnSuffix: null
handle: emailAddress
instructions: null
name: 'Email Address'
searchable: false
settings:
  validationRule: email
  variableName: EMAIL_ADDRESS
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\EnvironmentVariableField
