columnSuffix: null
handle: faqs
instructions: null
name: FAQs
searchable: true
settings:
  createButtonLabel: 'New FAQ'
  defaultIndexViewMode: cards
  entryTypes:
    - 97742dae-23f0-4986-a259-c886b727a452 # FAQ
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
