columnSuffix: null
handle: features
instructions: null
name: Features
searchable: true
settings:
  createButtonLabel: 'New feature'
  entryTypes:
    - 24a1d709-9601-4848-9deb-6df1f3ecd806 # Feature
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  siteSettings:
    __assoc__:
      -
        - dbf50cb2-37c8-45f7-b375-dcb93e09691b # Deutsch
        -
          __assoc__:
            -
              - uriFormat
              - '{parent.url}/features/{tagline|kebab}'
            -
              - template
              - _entries/feature
      -
        - 5b0c38db-9ab4-47d8-b4a7-913710c08ca6 # English
        -
          __assoc__:
            -
              - uriFormat
              - '{parent.url}/features/{tagline|kebab}'
            -
              - template
              - _entries/feature
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
