columnSuffix: null
handle: heroArea
instructions: 'The first published Hero Area will be used'
name: 'Hero Area'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Select a hero area'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692'
    - 'section:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
