columnSuffix: zeihvxvn
handle: heroAreaTemplate
instructions: null
name: 'Hero Area Template'
searchable: false
settings:
  includeDirectory: _layouts/partials/heroarea
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\IncludeField
