columnSuffix: rizfjoen
handle: imageAspectRatio
instructions: null
name: 'Image Aspect Ratio'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Default (16/9)'
        -
          - value
          - default
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Full Height'
        -
          - value
          - fullHeight
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - square
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Slim (21/9)'
        -
          - value
          - slim
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Classic (4/3)'
        -
          - value
          - classic
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
