columnSuffix: zfsxfdkz
handle: imageSource
instructions: 'Internal only. Name of a Microstock service of agency, if it differs from the copyright notice.'
name: 'Image Source'
searchable: false
settings:
  byteLimit: 250
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
