columnSuffix: dkaiswba
handle: isFeatured
instructions: 'Show in hero area of the article index page'
name: 'Is Featured'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
