columnSuffix: gollssan
handle: menuTitle
instructions: 'Short title for menu'
name: 'Menu Title'
searchable: true
settings:
  byteLimit: null
  charLimit: 30
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
