columnSuffix: tuizefdr
handle: navItemTemplate
instructions: 'The template that renders the dropdown panel. If empty, the direct descendants of this entry will be shown.'
name: 'Nav Item Template'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
