columnSuffix: wjuxwjsu
handle: parameter
instructions: 'Parameters in JSON-Format that will be available to the template'
name: Parameter
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
