columnSuffix: null
handle: persons
instructions: null
name: Persons
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a person'
  showCardsInGrid: true
  showSiteMenu: false
  sources:
    - 'section:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
