columnSuffix: null
handle: person
instructions: null
name: Person
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Select a person'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
