columnSuffix: xkuyhmpj
handle: positionAlign
instructions: null
name: 'Position Align'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
