columnSuffix: ticlfxhq
handle: primary
instructions: null
name: 'Primary Button'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
