columnSuffix: qrdzpvoi
handle: question
instructions: null
name: 'FAQs - FAQ - Question'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
