columnSuffix: null
handle: seoFields
instructions: 'Add SEO settings to overwrite default SEO content'
name: 'SEO Fields'
searchable: true
settings:
  createButtonLabel: 'Show SEO fields'
  defaultIndexViewMode: cards
  entryTypes:
    - 1c948380-c11c-45f9-a668-2a5eac6f24c9 # Settings
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
