columnSuffix: oiccxzkd
handle: showHeroArea
instructions: null
name: 'Show Hero Area'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
