columnSuffix: otzweros
handle: showStructureNavigation
instructions: 'Show navigation for this entry and it''s descendants'
name: 'Show Structure Navigation'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
