columnSuffix: bvyvbpkh
handle: showInSites2
instructions: null
name: 'Body Content - Image - Show in Sites'
searchable: false
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\SiteField
