columnSuffix: hlykmjun
handle: storyHeadingStyle
instructions: null
name: 'Story Heading Style'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Quotation marks'
        -
          - value
          - quoted
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
