columnSuffix: zybjsdrz
handle: storyTitleTemplate
instructions: null
name: 'Story Title Template'
searchable: false
settings:
  includeDirectory: _entries/article_story/title
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\IncludeField
