columnSuffix: hlykmjun
handle: style3
instructions: null
name: 'Story Content - Heading - Style'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Quotation marks'
        -
          - value
          - quoted
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
