columnSuffix: null
handle: target
instructions: null
name: 'Target Entry'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Select entry'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # Article
    - 'section:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
