columnSuffix: paidlzyc
handle: template
instructions: 'Project specific template. Refer to your docs for possible values.'
name: 'Dynamic Block Template'
searchable: false
settings:
  includeDirectory: _blocks/dynamic
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\IncludeField
