columnSuffix: zvkjsfie
handle: testimonialStyle
instructions: null
name: 'Testimonial Style'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'With overlapping image'
        -
          - value
          - overlappingImage
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'With large avatar'
        -
          - value
          - largeAvatar
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
