columnSuffix: null
handle: text5
instructions: null
name: 'Body Content - Heading - Text'
searchable: true
settings:
  byteLimit: 255
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
