columnSuffix: null
handle: topics
instructions: null
name: Topics
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a topic'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
