columnSuffix: qmwcncnc
handle: videoAspectRatio
instructions: 'Sets the aspect ratio for the video iframe'
name: 'Video Aspect Ratio'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '16:9'
        -
          - value
          - '16:9'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '21:9'
        -
          - value
          - '21:9'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4:3'
        -
          - value
          - '4:3'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
