columnSuffix: null
handle: writers
instructions: null
name: Writers
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'group:8f596240-23ec-46cd-abe2-386291b11179' # Content Editors
    - 'group:938701ef-3a45-4190-80fc-9326e9cf6f3b' # Writer
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Users
