assets:
  tempVolumeUid: ed627edd-73bd-4b75-8684-f410bf4e4b9d
dateModified: 1725518384
elementSources:
  craft\elements\Asset:
    -
      heading: Site
      type: heading
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf'
        - 'field:eb6b24cc-83d7-416f-be4b-d002c7688b58'
        - imageSize
        - dateModified
      type: native
    -
      heading: Internal
      type: heading
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:ed627edd-73bd-4b75-8684-f410bf4e4b9d'
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf'
        - imageSize
        - dateModified
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:3b60e4f9-36bb-4456-bee5-67160b5a3108' # User Photos
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf'
        - imageSize
        - dateModified
      type: native
    -
      heading: Work
      type: heading
    -
      condition:
        class: craft\elements\conditions\assets\AssetCondition
        conditionRules:
          -
            class: craft\fields\conditions\TextFieldConditionRule
            fieldUid: cc3fbab0-826f-4aed-b2aa-eeaecc2964bf
            operator: empty
            uid: 8182e7e7-1f2a-4b12-abf5-9c937e885f4d
            value: ''
        elementType: craft\elements\Asset
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:8326efe2-6f9f-4744-a23b-76512dd63e7c'
      label: 'Missing Alt Text'
      tableAttributes:
        - imageSize
        - dateCreated
        - uploader
      type: custom
    -
      heading: 'Search & Filter'
      type: heading
    -
      condition:
        class: craft\elements\conditions\assets\AssetCondition
        conditionRules:
          -
            class: craft\elements\conditions\assets\FileTypeConditionRule
            operator: in
            uid: f7614fdc-9370-4690-b14f-7a1c1baad092
            values:
              - image
          -
            class: craft\elements\conditions\assets\VolumeConditionRule
            operator: in
            uid: 6fbb3945-4a0d-4747-9471-4acbadf79393
            values:
              - 5a0be839-14a2-465e-a504-bb63dd0281e9 # Images
        elementType: craft\elements\Asset
        fieldContext: global
      defaultSort:
        - dateCreated
        - desc
      key: 'custom:0d3bd914-adcd-42cd-863b-d186c5a31bb8'
      label: 'All Images'
      tableAttributes:
        - imageSize
        - location
        - dateCreated
        - link
      type: custom
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: true
      key: '*'
      tableAttributes:
        - section
        - link
      type: native
    -
      heading: Site
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - section
        - bigFeaturedImage
        - 'field:eb6b24cc-83d7-416f-be4b-d002c7688b58'
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
      tableAttributes:
        - bigFeaturedImage
        - type
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # Article
      tableAttributes:
        - bigFeaturedImage
        - type
        - 'field:05ab0680-2ccc-4a59-932a-07311f773d42' # Topics
        - drafts
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
      tableAttributes:
        - bigPhoto
        - 'field:0767f000-e433-4930-9534-b795a48740bb' # Teaser
        - type
        - postDate
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
      tableAttributes:
        - type
        - postDate
        - link
      type: native
    -
      heading: Categories
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
      tableAttributes:
        - bigFeaturedImage
        - postDate
        - link
      type: native
    -
      heading: Embedded
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
      tableAttributes:
        - bigImage
        - 'field:0767f000-e433-4930-9534-b795a48740bb' # Teaser
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:80c4b0e7-c398-4776-ad74-df0f53d43c86' # Text Module
      tableAttributes:
        - slug
        - postDate
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:db16c9e5-2cfe-4821-88ff-7b18648846a1' # Testimonial
      tableAttributes:
        - type
        - 'field:013c1232-8bf7-4c1f-80dc-d456db31f159' # Testimonial Style
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:4d41f740-b1a9-477c-8522-85cf52b2652f' # Features
      tableAttributes:
        - 'field:0767f000-e433-4930-9534-b795a48740bb' # Teaser
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:ae6e4008-f45f-4d7d-bbc1-d8b90290efb8' # Team
      tableAttributes:
        - 'field:ee886fff-a72a-4a22-b217-f878c7f53ffe' # Persons
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:e3333efd-6726-41c1-9a66-a746a6f0d350' # Cards
      tableAttributes:
        - 'field:7602aac5-c98e-44bd-8570-457a85b8abad' # Criteria
        - postDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:4da24c3d-bc23-48bc-a26f-407730202ca7' # FAQs
      tableAttributes:
        - postDate
        - link
      type: native
    -
      heading: Work
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        elementType: craft\elements\Entry
        fieldContext: global
      key: 'custom:b512cb31-053f-43b8-8050-a309832e4558'
      label: 'My Drafts'
      tableAttributes: '-'
      type: custom
email:
  fromEmail: $EMAIL_ADDRESS
  fromName: $EMAIL_SENDER
  replyToEmail: null
  template: ''
  transportSettings:
    host: $SMTP_HOST
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    useAuthentication: $SMTP_AUTHENTICATION
    username: $SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
fs:
  imagesTransforms_local:
    hasUrls: true
    name: 'Images Transforms Local'
    settings:
      path: '@webroot/dist/transforms'
    type: craft\fs\Local
    url: '@weburl/dist/transforms'
  protectedVolumes_local:
    hasUrls: false
    name: 'Protected Volumes Local'
    settings:
      path: '@root/volumes'
    type: craft\fs\Local
    url: null
meta:
  __names__:
    0a4ca680-269a-45f0-8eac-eada97e7dc29: 'Single Line Text' # Single Line Text
    0c39cdb5-26f9-49ca-9bb4-445a28a61ddf: Images # Images
    0e5d9cbb-86fe-4e68-9632-75129c02b391: 'Short Text (not translatable)' # Short Text (not translatable)
    1b04edb4-5ebc-45da-ba85-afcd734f187b: 'YouTube Video' # YouTube Video
    1b464b23-6750-460e-aea1-0c4af5f52e23: Key # Key
    1c948380-c11c-45f9-a668-2a5eac6f24c9: Settings # Settings
    1dcc69f1-6963-4b8a-9a9a-10b35084db1a: Team # Team
    1de27fd9-bda6-4977-8d43-b36ef6813c60: Level # Level
    2a4edc9c-3738-408b-bf08-b557bc12ee6e: Style # Style
    2bbce5d5-c118-4901-9146-7f243a1b9116: Simple # Simple
    2bfd1710-35e5-41cb-a655-1fdaf49a0d7c: 'Featured Entries' # Featured Entries
    02d2113e-298a-47c6-a40e-413a682ac7c5: Question # Question
    2f93cb45-a9ce-4284-8848-9eb001fb8a1c: Article # Article
    2f9975bd-3ee0-4f17-96cc-e91a163964dc: 'Content Components' # Content Components
    3b60e4f9-36bb-4456-bee5-67160b5a3108: 'User Photos' # User Photos
    3bb09a1c-cb36-438e-b8d5-0b35b0965f4e: Default # Default
    3cb8a841-f986-4959-8f1a-c44fe16ff8d1: Answer # Answer
    3d8293ac-fa84-47ed-befa-a41cb6315212: Layout # Layout
    3db074a8-549b-4879-a864-250d2652282e: Cards # Cards
    4a8239eb-1b66-44e0-bd66-5a65d44b0727: Icon # Icon
    4b050685-0425-4094-bde2-85e2eedd0e12: Text # Text
    4bf7eb3c-ca42-4327-97e2-77533fc27a61: Caption # Caption
    4d41f740-b1a9-477c-8522-85cf52b2652f: Features # Features
    4da24c3d-bc23-48bc-a26f-407730202ca7: FAQs # FAQs
    5a0be839-14a2-465e-a504-bb63dd0281e9: Images # Images
    05ab0680-2ccc-4a59-932a-07311f773d42: Topics # Topics
    5b0c38db-9ab4-47d8-b4a7-913710c08ca6: English # English
    5e954ca4-2245-4624-b25e-fc91bbb917bf: Person # Person
    6bc951bf-74b3-4218-b3aa-dc427967abe9: Person # Person
    6ca3494d-cd87-4b86-a8fa-fbd8a0acab02: Story # Story
    6ecb9b3b-4c70-44df-a0ef-88a4ae27beec: Style # Style
    07a23de3-b713-43fc-8310-d9191d851801: Name # Name
    7b8b6f04-9d76-4b26-8276-96a80183750e: Quote # Quote
    7ef9424e-9902-4930-9244-8d7f93d6dc4b: 'Story Team' # Story Team
    7fb04ffe-73af-49d3-a840-c4c224d40dcf: Toggle # Toggle
    7fda4ce3-4bdd-4fbe-b32f-35a5e6707295: 'Article Index' # Article Index
    8b36e156-5078-4dac-b1d5-74d7b1e46eb9: 'Site Info' # Site Info
    8c826eca-f376-4f7a-92d6-307faddea123: Image # Image
    08f7545c-870e-4727-a418-660af19052ea: Buttons # Buttons
    8f596240-23ec-46cd-abe2-386291b11179: 'Content Editors' # Content Editors
    9c7e95a7-7a87-46ad-974e-8ce3846ef68b: Description # Description
    9e2e3c4b-bd17-46b3-97f0-a4f6605b93d9: Text # Text
    9efaa99a-273e-47a3-83f7-692251886873: Text # Text
    10ed7f90-b5ae-414d-a27e-ce0c2e680d27: Features # Features
    11f1c188-401c-44c4-bd0e-2b6d7b311fc6: Align # Align
    12ee7163-1896-4afc-b140-3f53c59f8b7d: Color # Color
    013c1232-8bf7-4c1f-80dc-d456db31f159: 'Testimonial Style' # Testimonial Style
    16e1ce60-0ee3-48c2-ac6a-d34757a52eed: 'Single Testimonial' # Single Testimonial
    24a1d709-9601-4848-9deb-6df1f3ecd806: Feature # Feature
    43f9aef9-cc98-45e1-ac64-8b73fc0c79a8: 'Topic Index' # Topic Index
    49a267d5-a7d3-43e8-979c-b4c3b107154e: Cover # Cover
    67a97a95-ddb9-4d73-a10b-649ba6d997cd: Privacy # Privacy
    71c1782e-c5bc-4d87-840e-0a4c1a643eff: 'Site Info' # Site Info
    72a3030d-cba4-4a39-ba7f-553d7116aeaf: Gallery # Gallery
    80c4b0e7-c398-4776-ad74-df0f53d43c86: 'Text Module' # Text Module
    80e88b1c-5efc-40b5-b15f-db6921165b73: Title # Title
    80fa81e4-1f78-4d88-b733-f565d1f5b9bd: Image # Image
    81e6a0d6-13c5-47ad-a9e6-c2181276db9c: Text # Text
    84b98802-2548-4aed-b67e-fc97f6ed9e30: Page # Page
    94b76905-09aa-4aeb-82a0-222f592d42f8: 'Show in Sites' # Show in Sites
    324e8b16-2907-4fe0-99bb-9d46526eec07: Addresses # Addresses
    354b3c11-ae38-4fae-8017-8ddced25fecd: Text # Text
    400d2e7a-d260-459d-b16d-bc388f093106: Tagline # Tagline
    489e5502-a241-4b2e-97c5-d8a0220a72c6: Target # Target
    518aea6d-af2d-4e4e-8d4b-a2ca618cd89c: Style # Style
    605e973b-b2e9-4421-9f1a-80d4cddc0cf0: Parameter # Parameter
    621ad41b-f019-4e95-96aa-49f8c56482db: 'SEO Descriction' # SEO Descriction
    735b5e6e-8026-4de4-8e32-14e03d975565: Image # Image
    0767f000-e433-4930-9534-b795a48740bb: Teaser # Teaser
    806a473e-c6e7-42cd-a76b-758ed48b5a2b: Role # Role
    871e0a60-ea70-4650-91f2-746c9bc2de41: 'Aspect Ratio' # Aspect Ratio
    956fbff8-1bb5-4c5d-8e58-ec36d77bf04e: Custom # Custom
    2232a9d8-f828-47e8-bb32-6e03f1cd70b6: 'Team Member' # Team Member
    3468bd44-82e8-4104-932e-5085601fca12: Legal # Legal
    4113a0a0-cb21-4671-9f9c-65575d18e024: 'Multiple Testimonials' # Multiple Testimonials
    6193ce57-a570-451e-8124-ec3ba985b0b2: Caption # Caption
    6739b2cb-a865-433d-9732-cdd6a419188d: 'Page Template' # Page Template
    7602aac5-c98e-44bd-8570-457a85b8abad: Criteria # Criteria
    7681df0f-bb10-47a5-ae54-25d7743237e3: 'Content Components' # Content Components
    8833ee2a-8239-453f-9996-a3af3eabb404: Heading # Heading
    13852c19-7f9e-4e6b-8790-0063f0f21ab8: 'Hero Area' # Hero Area
    37283b65-80b3-4451-a1d2-03fd68d18a05: 'Content Components' # Content Components
    52144f06-b394-45aa-bee6-d00e1f86878f: Primary # Primary
    75980a78-5a14-4d80-8e9c-b0616d62e02e: 'Hero Area' # Hero Area
    78014c80-5d4b-4253-ae59-80f00e516c86: Photo # Photo
    82752d41-f482-42da-b6c0-b1faa9b1aa1c: 'Grid Style' # Grid Style
    90724a6b-55ad-446f-be50-7aea7e1fb067: Robots # Robots
    97742dae-23f0-4986-a259-c886b727a452: FAQ # FAQ
    367161e2-88c5-4828-92ff-9124ef18da28: Image # Image
    0415563b-b1b2-4756-9f8d-0b86d005deb1: Heading # Heading
    655243f7-46a2-42c0-8de4-188017c31d53: 'Hero Area Template' # Hero Area Template
    938701ef-3a45-4190-80fc-9326e9cf6f3b: Writer # Writer
    5042338b-5f7b-4535-96bb-578a829e987c: Topic # Topic
    5286148d-12b9-4f55-a35c-0e51c06bbe44: Contact # Contact
    8785637f-8785-4fd2-86d2-9232d9674420: 'Related Entries' # Related Entries
    27127353-b8d1-4c07-a2af-7a273ad8f1f6: 'Hero Area' # Hero Area
    33518692-b4a6-4ac6-9423-5631e47f87a5: 'Position Align' # Position Align
    34581043-4880-49b9-b16a-cba691fa21f3: Image # Image
    69164545-5879-454d-a57e-f703ca431331: Image # Image
    85898001-9c9c-4d46-abf9-a928e44f0d48: 'Body Content' # Body Content
    95358052-5e25-4a5d-bd52-58078b1a5aa2: FAQs # FAQs
    97881295-fc14-4543-bb41-555ad6247d0d: Text # Text
    a05a3ce8-0bcb-4e36-abb0-1338754baec1: 'Image Align' # Image Align
    a08f1c5e-b057-468b-b989-6b243df4d213: Dynamic # Dynamic
    a4fff836-97c9-4c02-b970-c6f28915d8d0: Text # Text
    a3142d55-72d3-47df-ba3b-36c89ca45781: Writers # Writers
    abd279ac-58c4-41dc-ac32-d2e388e34252: Legal # Legal
    abefa0bd-6b36-4b4f-a9de-a4304e7b66a3: 'Public Schema' # Public Schema
    ac457f93-1a50-473e-9983-a899a7f0bed7: Heading # Heading
    adec5a84-87fd-49ac-85be-dd1870e7a3a5: Random # Random
    ae6e4008-f45f-4d7d-bbc1-d8b90290efb8: Team # Team
    af9afec0-f712-4b14-b235-851c6455e267: Text # Text
    b0cfc7f4-d446-41bb-87ab-dc16b1481540: 'Alternative Title' # Alternative Title
    b32ea3bc-ee43-4236-864d-972d36f184b2: Sitemap # Sitemap
    b40353f4-de5f-4006-813a-15494e63e104: Align # Align
    b7361735-c91d-4877-a975-cfe6751133b1: Cards # Cards
    bbe2ff0f-6056-4848-80de-3070bb80294d: Email # Email
    bf3d514d-a34d-41d6-bb20-61c6d8119820: 'Social Links' # Social Links
    bff90088-ffd2-4e25-aa4d-d9dc27cad56a: 'Column Content' # Column Content
    c0fe6eff-5323-415f-81d9-4f9d42a07b66: 'Story Content' # Story Content
    c8a6470e-a8da-46c4-ae23-4eb68d320a66: 'Show in Sites' # Show in Sites
    c38ac7d1-9663-45a2-a78e-c676b354e27e: Search # Search
    c72e758a-f6c3-42cd-896b-3ff6353ed259: 'Featured Image' # Featured Image
    c5912111-be84-47af-8f06-5df24eb99d67: 'Text (not translatable)' # Text (not translatable)
    cb919462-37df-4bb3-acf9-09892c4575e5: 'Nav Item' # Nav Item
    cf1158bf-b524-4684-9147-0ca8295ba477: Text # Text
    d3f37f0d-7675-4e3b-a223-69995d7b57b6: 'Text Module' # Text Module
    d92e63b4-996e-4dcd-8b55-d119540b5831: Article # Article
    d1935046-3734-43ba-934d-7512ecd81205: 'Cookie Consent' # Cookie Consent
    db16c9e5-2cfe-4821-88ff-7b18648846a1: Testimonial # Testimonial
    db33cf09-8ba1-45f6-9cc0-3e855cbcb809: Template # Template
    dbf50cb2-37c8-45f7-b375-dcb93e09691b: Deutsch # Deutsch
    dfe29fea-361a-48b4-b260-f547abb65701: Text # Text
    dfe86fae-c542-4ae2-8b07-16d57c206b16: Button # Button
    e2e51276-3783-49cb-9ed0-22ae364fd49a: 'Menu Title' # Menu Title
    e5bf7587-80f3-47bf-8e22-d1d8bbcf11ee: Template # Template
    e62d63b0-c299-42ce-aeef-86a69f7e676c: 'SEO Fields' # SEO Fields
    e3333efd-6726-41c1-9a66-a746a6f0d350: Cards # Cards
    eb61b6c1-d43a-4bf6-8091-bc71c44a9dcf: Entries # Entries
    eb276acd-66e3-48af-88d8-8ed2854da137: Topic # Topic
    ebe8548f-7f01-49b6-af98-56da49668e79: Logo # Logo
    edae774c-4600-499d-8c26-3af51f7bc820: Features # Features
    ee6f8d07-ca81-4da0-991c-491e5108bff8: Home # Home
    ee886fff-a72a-4a22-b217-f878c7f53ffe: Persons # Persons
    f3c6560d-3487-4f65-a4f9-ac2926397b57: 'Aspect Ratio' # Aspect Ratio
    f8ff18c6-ca19-4910-8753-62aa768dd3a3: Cite # Cite
    f26d4aac-c7ec-4b8f-98c8-ab7fc5315445: Testimonials # Testimonials
    f76ccc3a-7c88-43a3-9024-5ea619356bbf: Heading # Heading
    f620927d-baf7-430a-a965-f1e9ea676b83: Text # Text
    fad1f43f-1f3b-4f91-a3d7-fc97622b7767: FAQs # FAQs
    fbf00eb2-4a16-40ca-96bb-3fadd2bf459c: Page # Page
    fcbda6e5-a26a-4efb-800a-a67a44a88fa1: Person # Person
    fd509893-48ca-4ba0-a755-294ff5a48ca7: 'Two columns with image' # Two columns with image
    fea320b1-c261-431e-b670-048f10cf5285: Image # Image
plugins:
  _extras:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      bodyFontSize: ''
      customCss: ''
      diffContext: 1
      diffDetailLevel: word
      diffIgnoreCase: false
      diffIgnoreWhitespace: true
      diffLineNumbers: true
      diffMergeThreshold: 0.8
      diffRendererName: Combined
      diffSeparateBlock: true
      diffShowHeader: false
      enableCollectionMakros: true
      enableConditionRules: true
      enableCpAssets: false
      enableDraftHelpers: true
      enableElementActions: true
      enableElementmap: true
      enableExtrasVariable: true
      enableFieldLayoutElements: true
      enableOwnerPath: true
      enableRestoreDismissedTips: true
      enableSidebarVisibility: true
      enableTwigExtension: true
      enableWidgets: true
      showAllSites: true
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message'
      successFlashMessage: 'Thank you for your message! We received it and will reply as soon as possible.'
      toEmail: $EMAIL_ADDRESS
  contentoverview:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: 30
  schemaVersion: 5.3.0.2
  timeZone: $SYSTEM_TIMEZONE
