#!/bin/bash

if [ -z $3 ]
then
    echo Usage: install project-name username password
    exit 1
fi

echo Installing project $1...

cp .env.example .env &&
ddev config --project-name=$1 &&
ddev start &&
ddev composer install &&
ddev craft install --interactive=0 --username=$2 --password=$3 --email=admin@example.com &&
ddev craft index-assets/one images &&
echo Installing npm dependencies...
ddev exec npm install &&
ddev exec npm run build &&
ddev describe &&
echo Backing up empty database. Restore this if you want to start again with a clean state.
ddev craft db/backup /var/www/html/storage/custom-backups/empty.sql --zip --overwrite &&
ddev craft main/init
ddev launch
