defaultPlacement: end
enableVersioning: true
entryTypes:
  - d92e63b4-996e-4dcd-8b55-d119540b5831 # Article
  - 6ca3494d-cd87-4b86-a8fa-fbd8a0acab02 # Story
handle: article
maxAuthors: 3
name: Article
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Article Index'
      -
        - urlFormat
        - '{{ craft.entries.section(''page'').type(''articleIndex'').site(object.site).one.url }}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Card Preview'
      -
        - urlFormat
        - 'cp/preview-card?id={id}&siteId={object.site.id}&showMetaData=1'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # English
    enabledByDefault: true
    hasUrls: true
    template: _entries/article
    uriFormat: 'articles/{slug}'
  dbf50cb2-37c8-45f7-b375-dcb93e09691b: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _entries/article
    uriFormat: 'artikel/{slug}'
type: channel
