defaultPlacement: end
enableVersioning: true
entryTypes:
  - d1935046-3734-43ba-934d-7512ecd81205 # Cookie Consent
  - 67a97a95-ddb9-4d73-a10b-649ba6d997cd # Privacy
  - 3468bd44-82e8-4104-932e-5085601fca12 # Legal
handle: legal
maxAuthors: 1
name: Legal
propagationMethod: all
siteSettings:
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/legal
    uriFormat: '{slug}'
  dbf50cb2-37c8-45f7-b375-dcb93e09691b: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/legal
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 97678d3e-ee59-40cd-a9fb-262f8f0e8f8c
type: structure
