defaultPlacement: end
enableVersioning: true
entryTypes:
  - fbf00eb2-4a16-40ca-96bb-3fadd2bf459c # Page
  - ee6f8d07-ca81-4da0-991c-491e5108bff8 # Home
  - 5286148d-12b9-4f55-a35c-0e51c06bbe44 # Contact
  - 7fda4ce3-4bdd-4fbe-b32f-35a5e6707295 # Article Index
  - 43f9aef9-cc98-45e1-ac64-8b73fc0c79a8 # Topic Index
  - c38ac7d1-9663-45a2-a78e-c676b354e27e # Search
  - b32ea3bc-ee43-4236-864d-972d36f184b2 # Sitemap
  - cb919462-37df-4bb3-acf9-09892c4575e5 # Nav Item
  - 6739b2cb-a865-433d-9732-cdd6a419188d # Page Template
  - adec5a84-87fd-49ac-85be-dd1870e7a3a5 # Random
handle: page
maxAuthors: 1
name: Page
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # English
    enabledByDefault: true
    hasUrls: true
    template: _entries/page
    uriFormat: "{parent.uri|replace({'__home__': ''})}/{slug}"
  dbf50cb2-37c8-45f7-b375-dcb93e09691b: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _entries/page
    uriFormat: "{parent.uri|replace({'__home__': ''})}/{slug}"
structure:
  maxLevels: null
  uid: 90b11039-2eba-48d9-9e4a-bcbb8797204c
type: structure
