defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5e954ca4-2245-4624-b25e-fc91bbb917bf # Default
  - 81e27c57-c550-407d-bd6b-61aba2df6af4 # Profile
handle: person
maxAuthors: 1
name: Person
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/customconfig
    uriFormat: 'people/{slug}'
  dbf50cb2-37c8-45f7-b375-dcb93e09691b: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/customconfig
    uriFormat: 'leute/{slug}'
type: channel
