defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8b36e156-5078-4dac-b1d5-74d7b1e46eb9 # Site Info
handle: siteInfo
maxAuthors: 1
name: 'Site Info'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  dbf50cb2-37c8-45f7-b375-dcb93e09691b: # Deutsch
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
